######################################################################
# Automatically generated by qmake (3.0) Tue Nov 16 12:39:20 2021
######################################################################

QT+=opengl
LIBS += -lGLU
TEMPLATE = app
TARGET = IKcw
INCLUDEPATH += "$$PWD/eigen-3.4.0"
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += mainwindow.h widget.h bvhio.h Cartesian3.h
SOURCES += main.cpp mainwindow.cpp widget.cpp bvhio.cpp Cartesian3.cpp
